// ignore_for_file: lines_longer_than_80_chars

const Set<String> sentences = {
  'The bird had a belief that it was really a groundhog.',
  'For the 216th time, he said he would quit drinking soda after this last Coke.',
  'Tom got a small piece of pie.',
  'Eating eggs on Thursday for choir practice was recommended.',
  'There were a lot of paintings of monkeys waving bamboo sticks in the gallery.',
  'The opportunity of a lifetime passed before him as he tried to decide between a cone or a cup.',
  'Everyone pretends to like wheat until you mention barley.',
  'A quiet house is nice until you are ordered to stay in it for months.',
  'She was only made the society president because she can whistle with her toes.',
  'Today is the day I\'ll finally know what brick tastes like.',
  'Never underestimate the willingness of the greedy to throw you under the bus.',
  'When I was little I had a car door slammed shut on my hand and I still remember it quite vividly.',
  'On a scale from one to ten, what\'s your favorite flavor of random grammar?.',
  'I made myself a peanut butter sandwich as I didn\'t want to subsist on veggie crackers.',
  'He went back to the video to see what had been recorded and was shocked at what he saw.',
  'She borrowed the book from him many years ago and hasn\'t yet returned it.',
  'Yeah, I think it\'s a good environment for learning English.',
  'The group quickly understood that toxic waste was the most effective barrier to use against the zombies.',
  'Waffles are always better without fire ants and fleas.',
  'The fox in the tophat whispered into the ear of the rabbit.',
  'He was 100% into fasting with her until he understood that meant he couldn\'t eat.',
  'He found the chocolate covered roaches quite tasty.',
  'Car safety systems have come a long way, but he was out to prove they could be outsmarted.',
  'Two seats were vacant.',
  'The ice-cream trucks bring back bad memories for all of us.',
  'The blinking lights of the antenna tower came into focus just as I heard a loud snap.',
  'I\'ve never seen a more beautiful brandy glass filled with wine.',
  'It doesn\'t sound like that will ever be on my travel list.',
  'Each person who knows you has a different perception of who you are.',
  'She couldn\'t decide of the glass was half empty or half full so she drank it.',
  'The secret code they created made no sense, even to them.',
  'He shaved the peach to prove a point.',
  'I am counting my calories, yet I really want dessert.',
  'He stomped on his fruit loops and thus became a cereal killer.',
  'She saw no irony asking me to change but wanting me to accept her for who she is.',
  'She traveled because it cost the same as therapy and was a lot more enjoyable.',
  'He waited for the stop sign to turn to a go sign.',
  'She had a difficult time owning up to her own crazy self.',
  'He was disappointed when he found the beach to be so sandy and the sun so sunny.',
  'They were excited to see their first sloth.',
  'She had convinced her kids that any mushroom found on the ground would kill them if they touched it.',
  'She works two jobs to make ends meet; at least, that was her reason for not having time to join us.',
  'I\'d rather be a bird than a fish.',
  'She wanted a pet platypus but ended up getting a duck and a ferret instead.',
  'That was how he came to win \$1 million.',
  'Siri became confused when we reused to follow her directions.',
  'The rain pelted the windshield as the darkness engulfed us.',
  'Please tell me you don\'t work in a morgue.',
  'Most shark attacks occur about 10 feet from the beach since that\'s where the people are.',
  'The tree fell unexpectedly short.',
  'Flesh-colored yoga pants were far worse than even he feared.',
  'The water flowing down the river didn’t look that powerful from the car.',
  'Abstraction is often one floor above you.',
  'You\'re good at English when you know the difference between a man eating chicken and a man-eating chicken.',
  'He decided to fake his disappearance to avoid jail.',
  'Don\'t put peanut butter on the dog\'s nose.',
  'Dan took the deep dive down the rabbit hole.',
  'There are over 500 starfish in the bathroom drawer.',
  'Nancy decided to make the porta-potty her home.',
  'The snow-covered path was no help in finding his way out of the back-country.',
  'Excitement replaced fear until the final moment.',
  'The dead trees waited to be ignited by the smallest spark and seek their revenge.',
  'The door slammed on the watermelon.',
  'He learned the hardest lesson of his life and had the scars, both physical and mental, to prove it.',
  'I can\'t believe this is the eighth time I\'m smashing open my piggy bank on the same day!.',
  'They say people remember important moments in their life well, yet no one even remembers their own birth.',
  'Wisdom is easily acquired when hiding under the bed with a saucepan on your head.',
  'The lake is a long way from here.',
  'I\'ve traveled all around Africa and still haven\'t found the gnu who stole my scarf.',
  'Not all people who wander are lost.',
  'Three years later, the coffin was still full of Jello.',
  'Potato wedges probably are not best for relationships.',
  'He dreamed of eating green apples with worms.',
  'Patricia found the meaning of life in a bowl of Cheerios.',
  'The light in his life was actually a fire burning all around him.',
  'Twin 4-month-olds slept in the shade of the palm tree while the mother tanned in the sun.',
  'After fighting off the alligator, Brian still had to face the anaconda.',
  'When he encountered maize for the first time, he thought it incredibly corny.',
  'She hadn\'t had her cup of coffee, and that made things all the worse.',
  'I may struggle with geography, but I\'m sure I\'m somewhere around here.',
  'I love eating toasted cheese and tuna sandwiches.',
  'She wanted to be rescued, but only if it was Tuesday and raining.',
  'Mary realized if her calculator had a history, it would be more embarrassing than her computer browser history.',
  'He loved eating his bananas in hot dog buns.',
  'He invested some skill points in Charisma and Strength.',
  'Three generations with six decades of life experience.',
  'She could hear him in the shower singing with a joy she hoped he\'d retain after she delivered the news.',
  'He poured rocks in the dungeon of his mind.',
  'Lets all be unique together until we realise we are all the same.',
  'He turned in the research paper on Friday; otherwise, he would have not passed the class.',
  'He\'s in a boy band which doesn\'t make much sense for a snake.',
  'Toddlers feeding raccoons surprised even the seasoned park ranger.',
  'She cried diamonds.',
  'He was sure the Devil created red sparkly glitter.',
  'The lyrics of the song sounded like fingernails on a chalkboard.',
  'He decided to live his life by the big beats manifesto.',
  'That is an appealing treasure map that I can\'t read.',
  'It caught him off guard that space smelled of seared steak.',
};
